export const plantCommonNames = [
  "Ageratum",
  "Aloe",
  "Amaranth",
  "Bamboo",
  "Basil",
  "Begonia",
  "Bonsai",
  "Cactus",
  "Caladium",
  "Carnation",
  "Chrysanthemum",
  "Daffodil",
  "Daisy",
  "Dandelion",
  "Delphinium",
  "Echinacea",
  "Elderberry",
  "Eucalyptus",
  "Euphorbia",
  "Fern",
  "Fiddle Leaf Fig",
  "Forsythia",
  "Fuchsia",
  "Gardenia",
  "Gazania",
  "Geranium",
  "Ginkgo",
  "Hellebore",
  "Hibiscus",
  "Hollyhock",
  "Honeysuckle",
  "Impatiens",
  "Iris",
  "Ivy",
  "Jacaranda",
  "Jade Plant",
  "Jasmine",
  "Jonquil",
  "Kaffir Lily",
  "Kale",
  "Kalanchoe",
  "Kangaroo Paw",
  "Lantana",
  "Lavender",
  "Lilac",
  "Lily of the Valley",
  "Maple",
  "Marigold",
  "Monstera",
  "Narcissus",
  "Nasturtium",
  "Nigella",
  "Oleander",
  "Orchid",
  "Oregano",
  "Pansy",
  "Petunia",
  "Queen Anne's Lace",
  "Quaking Grass",
  "Quince",
  "Rhododendron",
  "Rose",
  "Rudbeckia",
  "Sage",
  "Snapdragon",
  "Sunflower",
  "Tansy",
  "Thyme",
  "Tulip",
  "Umbrella Palm",
  "Umbrella Plant",
  "Umbrella Tree",
  "Verbena",
  "Vinca",
  "Wandering Jew",
  "Wisteria",
  "Xanthoceras",
  "Xmas Cactus",
  "Yarrow",
  "Yew",
  "Yucca",
  "Zamia",
  "Zebra Plant",
  "Zinnia"
  ];
  

  /* ChatGPT prompt was "I want a javascript array of 80 common names of plants. I do not want twice the same name." */